/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare export declare function asyncPlus100(input: bigint): Promise<bigint>

export declare export declare function plus100(input: number): number
