[package]
name = "workflow-engine-core"
version = "0.0.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
tokio.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }